#!/bin/bash

WATCHFILE=/tmp/colors/konsole
PROFILE_NAME='Profile 1'

if [ ! -f $WATCHFILE ]; then
    touch $WATCHFILE
fi

while inotifywait -q -e modify "$WATCHFILE" >/dev/null; do
    # Find all terminals to printf the command to
    terms=$(find /dev/pts/* | cut -f 1)
    colorscheme=$(cat $WATCHFILE)
    echo $colorscheme
    while read -r term; do
        coloroutput=$(konsoleprofile colors="$colorscheme")
        printf "%s" "$coloroutput" > "$term"
    done <<< "$terms"
done
