#!/bin/bash

swaylock \
	-f \
	--screenshots \
	--clock \
	--indicator \
	--indicator-radius 100 \
	--indicator-thickness 7 \
	--effect-blur 15x15 \
	--effect-vignette 0.5:0.5 \
	--grace 2 \
	--fade-in 0.2
