#!/bin/bash

xhost +local:

if [ "$1" == "" ]; then
    sudo systemd-nspawn \
        --bind-ro=/dev/dri \
        --bind=/tmp/.X11-unix \
        --bind=/home/frans/bin/MATLAB \
        --bind=/home/frans/Documents/school \
        --bind=/home/frans/Documents/extern_school \
        --bind-ro=/home/frans/.zshrc \
        --bind-ro=/home/frans/.screenrc \
        --bind-ro=/home/frans/.config/zsh \
        --bind-ro=/home/frans/Downloads \
        -b -D /opt/deb9
elif [ "$1" == "attach" ]; then
    sudo systemd-nspawn -D deb9
fi


