#!/bin/bash

# No, the telegram desktop process is actually called that
procastinators=("Discord" "telegram-deskto")

# Seed random generator
RANDOM=$$$(date +%s)

while true; do
    sleep_time=$((RANDOM % 60 + 30))
    echo "Killing next victim in ${sleep_time}"
    sleep ${sleep_time}
    victim=${procastinators[$RANDOM % ${#procastinators[@]} ]}
    if pgrep "${victim}" ; then
        notify-send "Killing ${victim} in 30 seconds"
        echo "Killing ${victim} in 30 seconds"
        sleep 30
        pkill "${victim}"
        echo "Victim dead, time to find another one"
    else
        echo "Victim was already dead ${victim}"
    fi
done
