#!/bin/bash
#8 is the id of the mouse
#find with xinput
id=$(xinput \
    | grep G502 \
    | grep '(2)' \
    | grep pointer \
    | head -n 2 \
    | sed 's/.*id=\(\d*\)/\1/g' \
    | awk '{print $1}')


while read -r id ; do
    echo "Setting id ${id}"

    xinput set-prop "$id" 'libinput Accel Profile Enabled' 0, 1
done <<< "$id"

# Fix wireless mouse

# Invert forward/back buttons, remap scrollwheel-left to mouse button
logitech_mouse_id=$(xinput | grep "MX Anywhere 2" | cut -d = -f 2 | cut -f 1 | head -n 1)
xinput set-button-map "$logitech_mouse_id" 1 2 3 4 5 2 7 9 8 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24

# Set sensitivity and acceleration
# xset m 1
